# Generated by Django 6.0.4 on 2026-05-08 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('processing', '生成中'), ('completed', '已完成'), ('failed', '生成失败')], default='processing', max_length=255, verbose_name='状态')),
                ('question_count', models.IntegerField(default=5, verbose_name='问题数量')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='notes.note', verbose_name='所属笔记')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL, verbose_name='发起用户')),
            ],
            options={
                'verbose_name': '测验记录',
                'verbose_name_plural': '测验记录',
                'db_table': 'quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.CharField(max_length=255, verbose_name='问题干')),
                ('options', models.JSONField(verbose_name='选项')),
                ('answer', models.CharField(max_length=255, verbose_name='答案')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='解析')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='notes.quiz', verbose_name='所属测验')),
            ],
            options={
                'verbose_name': '测验问题',
                'verbose_name_plural': '测验问题',
                'db_table': 'questions',
            },
        ),
    ]
