# Generated by Django 6.0.4 on 2026-05-09 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_add_quiz_and_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='得分')),
                ('total', models.IntegerField(default=5, verbose_name='总题数')),
                ('correct_rate', models.FloatField(default=0.0, verbose_name='正确率')),
                ('detail', models.JSONField(default=list, verbose_name='答题详情')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='完成时间')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='notes.quiz', verbose_name='所属测验')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '答题记录',
                'verbose_name_plural': '答题记录',
                'db_table': 'quiz_attempts',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='WrongQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=255, verbose_name='用户答案')),
                ('wrong_count', models.IntegerField(default=1, verbose_name='错题次数')),
                ('last_wrong_at', models.DateTimeField(auto_now=True, verbose_name='上次错题时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_questions', to='notes.question', verbose_name='错题')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_questions', to='notes.quiz', verbose_name='所属测验')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_questions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '错题记录',
                'verbose_name_plural': '错题记录',
                'db_table': 'wrong_questions',
                'ordering': ['-last_wrong_at'],
            },
        ),
    ]
