# Generated by Django 6.0.4 on 2026-05-09 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_add_QuizAttempt_WrongQuestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizattempt',
            old_name='detail',
            new_name='answers_detail',
        ),
    ]
