# Generated by Django 6.0.4 on 2026-05-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_update_detail_to_answersdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Celery任务ID'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('processing', '生成中'), ('completed', '已完成'), ('failed', '生成失败'), ('cancelled', '已取消')], default='processing', max_length=255, verbose_name='状态'),
        ),
    ]
