# Generated by Django 6.0.4 on 2026-05-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_quiz_celery_task_id_alter_quiz_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('processing', '生成中'), ('completed', '已完成'), ('failed', '生成失败')], default='processing', max_length=255, verbose_name='状态'),
        ),
    ]
