# Generated by Django 6.0.4 on 2026-05-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_quiz_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='标签'),
        ),
    ]
