# Generated by Django 6.0.4 on 2026-07-13 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_fix_tags_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content_plain',
            field=models.TextField(verbose_name='笔记内容(纯文本格式)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=10, verbose_name='答案'),
        ),
        migrations.AlterField(
            model_name='question',
            name='stem',
            field=models.TextField(verbose_name='问题干'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='notes.note', verbose_name='所属笔记'),
        ),
        migrations.AddConstraint(
            model_name='wrongquestion',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='uq_wrong_user_question'),
        ),
    ]
